@c -*-texinfo-*-
@c This is part of the GNU Gbank Reference Manual.
@c Copyright (C) 2016 Free Software Foundation, Inc.


@copying
This manual documents GNU Gbank version @value{VERSION}.

Copyright (C) 2016 Free Software Foundation, Inc.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A
copy of the license is included in the section entitled ``GNU Free
Documentation License.''
@end copying


@defindex ei


@node Enum Info
@subsection Enum Info

Gbank Enum Info low level API.@*
GIEnumInfo — Structs representing an enumeration and its values.


@subheading Description

@code{GIEnumInfo} represents an argument. An argument is always part of a
@code{GICallableInfo}.


@subheading Struct Hierarchy

@indentedblock
GIBaseInfo           	       		@*
@ @ +--- GIRegisteredTypeInfo  		@*
@ @ @ @ @ @ @ @ @ @ @  +--- GIEnumInfo
@end indentedblock


@subheading Procedures

@indentedblock
@table @code
@item @ref{gbank-enum-import}
@item @ref{gbank-ei-get-n-values}
@item @ref{gbank-ei-get-value}
@item @ref{gbank-ei-get-n-methods}
@item @ref{gbank-ei-get-method}
@item @ref{gbank-vi-get-value}
@end table
@end indentedblock

Note: in this section, unless otherwise specified, the @var{info}
argument is [must be] a pointer to a @code{GIEumInfo}.


@anchor{gbank-enum-import}
@deffn Procedure gbank-enum-import info

Returns a @code{<genum>} instance.

Obtain the values this enumeration contains and construct ...
@end deffn


@anchor{gbank-ei-get-n-values}
@deffn Procedure gbank-ei-get-n-values info

Returns the number of values.

Obtain the number of values this enumeration contains.
@end deffn


@anchor{gbank-ei-get-value}
@deffn Procedure gbank-ei-get-value info index

Returns a pointer to a @code{GIValueInfo} or #f if type tag is wrong.

Obtain a value for this enumeration.  The @code{GIValueInfo} must be
free'd using @code{gbank-bi-unref} when done.

@var{index} is a 0-based offset into @var{info} for a value.
@end deffn


@anchor{gbank-ei-get-n-methods}
@deffn Procedure gbank-ei-get-n-methods info

Returns the number of methods.

Obtain the number of methods this enumeration has.
@end deffn


@anchor{gbank-ei-get-method}
@deffn Procedure gbank-ei-get-method info index

Returns a pointer to a @code{GIFunctionInfo} or #f if type tag is wrong.

Obtain a method for this enumeration.  The @code{GIFunctionInfo} must be
free'd using @code{gbank-bi-unref} when done.

@var{index} is a 0-based offset into @var{info} for a method.
@end deffn


@anchor{gbank-vi-get-value}
@deffn Procedure gbank-vi-get-value info

Returns the enumeration value.

Obtain a value of the @code{GIValueInfo}.

@var{info} is [must be] a pointer to a @code{GIValueInfo}.
@end deffn


@c @subheading Types and Values

@c @indentedblock
@c @table @code
@c @item @ref{%gbank-ai-transfer}
@c @end table
@c @end indentedblock


@c @anchor{%gbank-ai-transfer}
@c @defvar %gbank-ai-transfer

@c An instance of @code{<enum>}, who's members are the scheme
@c representation of the @code{GITransfer}:

@c @indentedblock
@c nothing		@*
@c container	@*
@c everything
@c @end indentedblock
@c @end defvar
