@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.
@c Copyright (C) 2016 - 2018 Free Software Foundation, Inc.
@c See the file g-golf.texi for copying conditions.


@node Type Information
@subsection Type Information

G-Golf GObject Type Information low level API.@*
Type Information — The GLib Runtime type identification and management system


@subheading Description

The @code{GType API} is the foundation of the GObject system. It
provides the facilities for registering and managing all fundamental
data types, user-defined object and interface types.

Please read the @uref{@value{UGOBJECT-Type-Info}, Type Information}
section from the GObject reference manual for a complete description.


@subheading Object Hierarchy

@indentedblock
gpointer           	       @*
@ @ +--- GType		       @*
@end indentedblock


@subheading Procedures

@indentedblock
@table @code
@item @ref{g-type-name}
@end table
@end indentedblock


@subheading Types and Values

@indentedblock
@table @code
@item @ref{%g-type-fundamental-flags}
@end table
@end indentedblock


@subheading Procedures


@anchor{g-type-name}
@deffn Procedure g-type-name type

Returns a string or @code{#f}.

Get the unique name that is assigned to a type ID. Note that this
function (like all other GType API) cannot cope with invalid type
IDs. It accepts validly registered type ID, but randomized type IDs
should not be passed in and will most likely lead to a crash.
@end deffn


@subheading Types and Values


@anchor{%g-type-fundamental-flags}
@defivar <gi-enum> %g-type-fundamental-flags

Bit masks used to check or determine specific characteristics of a
fundamental type.

An instance of @code{<gi-enum>}, who's members are the scheme
representation of the @code{GTypeFundamentalFlags}:

@indentedblock
@emph{gi-name}: GTypeFundamentalFlags  @*
@emph{scm-name}: g-type-fundamental-flags  @*
@emph{enum-set}:
@indentedblock
@table @code
@item classed
Indicates a classed type

@item instantiable
Indicates an instantiable type (implies classed)

@item derivable
Indicates a flat derivable type

@item deep-derivable
Indicates a deep derivable type (implies derivable)
@end table
@end indentedblock
@end indentedblock
@end defivar
