@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.  Copyright (C) 2019
@c Free Software Foundation, Inc.  See the file g-golf.texi for copying
@c conditions.


@c @defindex ei


@node Object
@subsection Object

G-Golf Object import high level API.@*
The G-Golf GI object import high level API.


@subheading Procedures

@indentedblock
@table @code
@item @ref{gi-import-object}
@end table
@end indentedblock


@c @subheading Variables

@c @indentedblock
@c @table @code
@c @item @ref{%gi-strip-boolean-result}
@c @end table
@c @end indentedblock


@c @subheading Description


@subheading Procedures

Note: in this section, the @var{info} argument is [must be] a pointer to
a @code{GIObjectInfo}.


@anchor{gi-import-object}
@deffn Procedure gi-import-object info

Returns nothing.

FIXME (largely incomplete) Imports @var{info} in Guile and exports its
interface.
@end deffn


@c @subheading Variables
