@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.
@c Copyright (C) 2016 - 2018 Free Software Foundation, Inc.
@c See the file g-golf.texi for copying conditions.


@defindex ei


@node Enum Info
@subsection Enum Info

G-Golf Enum Info low level API.@*
GIEnumInfo — Structs representing an enumeration and its values.


@subheading Description

@code{GIEnumInfo} represents an argument. An argument is always part of a
@code{GICallableInfo}.


@subheading Struct Hierarchy

@indentedblock
GIBaseInfo           	       		@*
@ @ +--- GIRegisteredTypeInfo  		@*
@ @ @ @ @ @ @ @ @ @ @  +--- GIEnumInfo
@end indentedblock


@subheading Procedures

@indentedblock
@table @code
@item @ref{g-golf-enum-import}
@item @ref{g-golf-enum-get-values}

@item @ref{g-golf-ei-get-n-values}
@item @ref{g-golf-ei-get-value}
@item @ref{g-golf-ei-get-n-methods}
@item @ref{g-golf-ei-get-method}

@item @ref{g-golf-vi-get-value}
@end table
@end indentedblock

Note: in this section, unless otherwise specified, the @var{info}
argument is [must be] a pointer to a @code{GIEumInfo}.


@anchor{g-golf-enum-import}
@deffn Procedure g-golf-enum-import info

Returns a @code{<genum>} instance.

Obtain the values this enumeration contains and construct a
@code{<genum>} instance.
@end deffn


@anchor{g-golf-enum-get-values}
@deffn Procedure g-golf-enum-get-values info

Returns a list of @code{(name . value)} @var{info} contains.

Obtain and build a list of pairs @code{(name . value)} this enumeration
contains.
@end deffn


@anchor{g-golf-ei-get-n-values}
@deffn Procedure g-golf-ei-get-n-values info

Returns the number of values.

Obtain the number of values this enumeration contains.
@end deffn


@anchor{g-golf-ei-get-value}
@deffn Procedure g-golf-ei-get-value info index

Returns a pointer to a @code{GIValueInfo} or #f if type tag is wrong.

Obtain a value for this enumeration.  The @code{GIValueInfo} must be
free'd using @code{g-golf-bi-unref} when done.

@var{index} is a 0-based offset into @var{info} for a value.
@end deffn


@anchor{g-golf-ei-get-n-methods}
@deffn Procedure g-golf-ei-get-n-methods info

Returns the number of methods.

Obtain the number of methods this enumeration has.
@end deffn


@anchor{g-golf-ei-get-method}
@deffn Procedure g-golf-ei-get-method info index

Returns a pointer to a @code{GIFunctionInfo} or #f if type tag is wrong.

Obtain a method for this enumeration.  The @code{GIFunctionInfo} must be
free'd using @code{g-golf-bi-unref} when done.

@var{index} is a 0-based offset into @var{info} for a method.
@end deffn


@anchor{g-golf-vi-get-value}
@deffn Procedure g-golf-vi-get-value info

Returns the enumeration value.

Obtain a value of the @code{GIValueInfo}.

@var{info} is [must be] a pointer to a @code{GIValueInfo}.
@end deffn


@c @subheading Types and Values

@c @indentedblock
@c @table @code
@c @item @ref{%g-golf-ai-transfer}
@c @end table
@c @end indentedblock


@c @anchor{%g-golf-ai-transfer}
@c @defvar %g-golf-ai-transfer

@c An instance of @code{<enum>}, who's members are the scheme
@c representation of the @code{GITransfer}:

@c @indentedblock
@c nothing		@*
@c container	@*
@c everything
@c @end indentedblock
@c @end defvar
