@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.
@c Copyright (C) 2016 - 2018 Free Software Foundation, Inc.
@c See the file g-golf.texi for copying conditions.


@defindex oi


@node Object Info
@subsection Object Info

G-Golf Object Info low level API.@*
GIObjectInfo — Structs representing a GObject.


@subheading Description

@code{GIObjectInfo} represents a @uref{@value{UGOBJECT-GObject-struct},
GObject}. This doesn't represent a specific instance of a GObject,
instead this represent the object type (eg class).

A GObject has methods, fields, properties, signals, interfaces,
constants and virtual functions.


@subheading Struct Hierarchy

@indentedblock
GIBaseInfo           	       		@*
@ @ +--- GIRegisteredTypeInfo  		@*
@ @ @ @ @ @ @ @ @ @ @  +--- GIObjectInfo
@end indentedblock


@subheading Procedures

@indentedblock
@table @code
@c @item @ref{g-golf-object-import}
@item @ref{g-golf-oi-get-abstract}
@item @ref{g-golf-oi-get-parent}
@item @ref{g-golf-oi-get-type-name}
@item @ref{g-golf-oi-get-n-constants}
@item @ref{g-golf-oi-get-constant}
@item @ref{g-golf-oi-get-n-fields}
@item @ref{g-golf-oi-get-field}
@item @ref{g-golf-oi-get-n-interfaces}
@item @ref{g-golf-oi-get-interface}
@item @ref{g-golf-oi-get-n-methods}
@item @ref{g-golf-oi-get-method}
@item @ref{g-golf-oi-find-method}
@item @ref{g-golf-oi-get-n-properties}
@item @ref{g-golf-oi-get-property}
@item @ref{g-golf-oi-get-n-signals}
@item @ref{g-golf-oi-get-signal}
@item @ref{g-golf-oi-find-signal}
@item @ref{g-golf-oi-get-n-vfuncs}
@item @ref{g-golf-oi-get-vfunc}
@item @ref{g-golf-oi-get-class-struct}
@end table
@end indentedblock

Note: in this section, unless otherwise specified, the @var{info}
argument is [must be] a pointer to a @code{GIObjectInfo}.


@c @anchor{g-golf-object-import}
@c @deffn Procedure g-golf-object-import info

@c Returns a @code{<gobject>} instance.

@c Obtain the values this objecteration contains and construct ...
@c @end deffn


@anchor{g-golf-oi-get-abstract}
@deffn Procedure g-golf-oi-get-abstract info

Returns #t if the @var{info} object type is abstract.

Obtain if the object type is an abstract type, eg if it cannot be
instantiated.
@end deffn


@anchor{g-golf-oi-get-parent}
@deffn Procedure g-golf-oi-get-parent info

Returns a pointer to the @var{info}'s parent @code{GIObjectInfo}.

Obtain the parent of the object type.
@end deffn


@anchor{g-golf-oi-get-type-name}
@deffn Procedure g-golf-oi-get-type-name info

Returns the name of the object type for @var{info}.

Obtain the name of the object class/type for @var{info}.
@end deffn


@anchor{g-golf-oi-get-n-constants}
@deffn Procedure g-golf-oi-get-n-constants info

Returns the number of constants for @var{info}.

Obtain the number of constants that this object type has.
@end deffn


@anchor{g-golf-oi-get-constant}
@deffn Procedure g-golf-oi-get-constant info n

Returns a pointer to the @var{n}th @code{GIConstantInfo} of @var{info}.

It must be freed by calling @ref{g-golf-bi-unref} when done accessing
the data.
@end deffn


@anchor{g-golf-oi-get-n-fields}
@deffn Procedure g-golf-oi-get-n-fields info

Returns the number of fields for @var{info}.

Obtain the number of fields that this object type has.
@end deffn


@anchor{g-golf-oi-get-field}
@deffn Procedure g-golf-oi-get-field info n

Returns a pointer to the @var{n}th @code{GIFieldInfo} of @var{info}.

It must be freed by calling @ref{g-golf-bi-unref} when done accessing
the data.
@end deffn


@anchor{g-golf-oi-get-n-interfaces}
@deffn Procedure g-golf-oi-get-n-interfaces info

Returns the number of interfaces for @var{info}.

Obtain the number of interfaces that this object type has.
@end deffn


@anchor{g-golf-oi-get-interface}
@deffn Procedure g-golf-oi-get-interface info n

Returns a pointer to the @var{n}th @code{GIInterfaceInfo} of @var{info}.

It must be freed by calling @ref{g-golf-bi-unref} when done accessing
the data.
@end deffn


@anchor{g-golf-oi-get-n-methods}
@deffn Procedure g-golf-oi-get-n-methods info

Returns the number of methods for @var{info}.

Obtain the number of methods that this object type has.
@end deffn


@anchor{g-golf-oi-get-method}
@deffn Procedure g-golf-oi-get-method info n

Returns a pointer to the @var{n}th @code{GIFunctionInfo} of @var{info}.

It must be freed by calling @ref{g-golf-bi-unref} when done accessing
the data.
@end deffn


@anchor{g-golf-oi-find-method}
@deffn Procedure g-golf-oi-find-method info name

Returns a pointer to a @code{GIFunctionInfo} or #f if there is no method
available with that name.

It must be freed by calling @ref{g-golf-bi-unref} when done accessing
the data.
@end deffn


@anchor{g-golf-oi-get-n-properties}
@deffn Procedure g-golf-oi-get-n-properties info

Returns the number of properties for @var{info}.

Obtain the number of properties that this object type has.
@end deffn


@anchor{g-golf-oi-get-property}
@deffn Procedure g-golf-oi-get-property info n

Returns a pointer to the @var{n}th @code{GIPropertyInfo} of @var{info}.

It must be freed by calling @ref{g-golf-bi-unref} when done accessing
the data.
@end deffn


@anchor{g-golf-oi-get-n-signals}
@deffn Procedure g-golf-oi-get-n-signals info

Returns the number of signals for @var{info}.

Obtain the number of signals that this object type has.
@end deffn


@anchor{g-golf-oi-get-signal}
@deffn Procedure g-golf-oi-get-signal info n

Returns a pointer to the @var{n}th @code{GISignalInfo} of @var{info}.

It must be freed by calling @ref{g-golf-bi-unref} when done accessing
the data.
@end deffn


@anchor{g-golf-oi-find-signal}
@deffn Procedure g-golf-oi-find-signal info name

Returns a pointer to a @code{GISignalInfo} or #f if there is no signal
available with that name.

It must be freed by calling @ref{g-golf-bi-unref} when done accessing
the data.
@end deffn


@anchor{g-golf-oi-get-n-vfuncs}
@deffn Procedure g-golf-oi-get-n-vfuncs info

Returns the number of vfuncs for @var{info}.

Obtain the number of vfuncs that this object type has.
@end deffn


@anchor{g-golf-oi-get-vfunc}
@deffn Procedure g-golf-oi-get-vfunc info n

Returns a pointer to the @var{n}th @code{GIVfuncInfo} of @var{info}.

It must be freed by calling @ref{g-golf-bi-unref} when done accessing
the data.
@end deffn


@anchor{g-golf-oi-get-class-struct}
@deffn Procedure g-golf-oi-get-class-struct info

Returns a pointer to the @var{n}th @code{GIStructInfo} of @var{info}, or
#f.

Every @code{GObject} has two structures: an instance structure and a
class structure. This function returns a pointer to the @var{info} class
structure.

It must be freed by calling @ref{g-golf-bi-unref} when done accessing
the data.
@end deffn


@c @subheading Types and Values

@c @indentedblock
@c @table @code
@c @item @ref{%g-golf-ai-transfer}
@c @end table
@c @end indentedblock


@c @anchor{%g-golf-ai-transfer}
@c @defvar %g-golf-ai-transfer

@c An instance of @code{<object>}, who's members are the scheme
@c representation of the @code{GITransfer}:

@c @indentedblock
@c nothing		@*
@c container	@*
@c everything
@c @end indentedblock
@c @end defvar
