@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.
@c Copyright (C) 2016 - 2018 Free Software Foundation, Inc.
@c See the file g-golf.texi for copying conditions.


@c @defindex tl


@node Enumeration and Flag Types
@subsection Enumeration and Flag Types

G-Golf GObject Enumeration and Flag Types low level API.@*
Enumeration and Flag Types — Enumeration and flags types.


@subheading Description

The GLib type system provides fundamental types for enumeration and
flags types. (Flags types are like enumerations, but allow their values
to be combined by bitwise or). A registered enumeration or flags type
associates a name and a nickname with each allowed value. When an
enumeration or flags type is registered with the GLib type system, it
can be used as value type for object properties.


@c @subheading Procedures


@c @subheading Types and Values


@c @subheading Struct Hierarchy

@c @indentedblock
@c GIBaseInfo           	       		@*
@c @ @ +--- GIRegisteredTypeInfo  		@*
@c @ @ @ @ @ @ @ @ @ @ @  +--- GIEnumInfo
@c @end indentedblock
