@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.
@c Copyright (C) 2016 - 2018 Free Software Foundation, Inc.
@c See the file g-golf.texi for copying conditions.


@c @defindex tl


@node The Main Event Loop
@subsection The Main Event Loop

G-Golf Glib Main Event Loop low level API.@*
The Main Event Loop — manages all available sources of events



@subheading Description

The main event loop manages all the available sources of events for GLib
and GTK+ applications. These events can come from any number of
different types of sources such as file descriptors (plain files, pipes
or sockets) and timeouts. New types of event sources can also be added
using @code{g-source-attach}.

Please read @uref{@value{UGLIB-Main-Event-Loop}, The Main Event Loop}
section from the Glib reference manual for a complete description.


@c @subheading Struct Hierarchy

@c @indentedblock
@c GIBaseInfo           	       		@*
@c @ @ +--- GIRegisteredTypeInfo  		@*
@c @ @ @ @ @ @ @ @ @ @ @  +--- GIEnumInfo
@c @end indentedblock


@subheading Procedures

@indentedblock
@table @code
@item @ref{g-main-loop-new}
@item @ref{g-idle-source-new}
@end table
@end indentedblock


@anchor{g-main-loop-new}
@deffn Procedure g-main-loop-new context is-running?

Returns a pointer to a new @code{GMainLoop}.

Creates a new @code{GMainLoop} structure.

The @var{context} must be a pointer to a @code{GMainContext} of
@code{#f}, in which case the default context is used.  When
@var{is-running?} is @code{#t}, it indicates that the loop is
running. This is not very important since calling @code{g-main-loop-run}
will set this to @code{#t} anyway.
@end deffn


@anchor{g-idle-source-new}
@deffn Procedure g-idle-source-new

Returns a pointer to a new @code{GSource}.

Creates a new idle source.

The source will not initially be associated with any @code{GMainContext}
and must be added to one with @code{g-source-attach} before it will be
executed. Note that the default priority for idle sources is @code{200},
as compared to other sources which have a default priority of
@code{300}.
@end deffn


@c @subheading Types and Values

@c @indentedblock
@c @table @code
@c @item @ref{<gi-enum>}
@c @end table
@c @end indentedblock
