@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.
@c Copyright (C) 2016 - 2018 Free Software Foundation, Inc.
@c See the file g-golf.texi for copying conditions.


@defindex fi


@node Function Info
@subsection Function Info

G-Golf Function Info low level API.@*
GIFunctionInfo — Struct representing a function.


@subheading Procedures

@indentedblock
@table @code
@item @ref{g-golf-fi-get-flags}
@item @ref{g-golf-fi-get-symbol}
@end table
@end indentedblock


@subheading Types and Values


@indentedblock
@table @code
@item @ref{%g-golf-fi-flags}
@end table
@end indentedblock


@subheading Struct Hierarchy

@indentedblock
GIBaseInfoInfo         	                     @*
@ @ +--- GICallableInfo	                     @*
@ @ @ @ @ @ @ @ @ @ @ +--- GIFunctionInfo    @*
@ @ @ @ @ @ @ @ @ @ @ +--- GISignalInfo      @*
@ @ @ @ @ @ @ @ @ @ @ +--- GIVFuncInfo
@end indentedblock


@subheading Description

@code{GIFunctionInfo} represents a function, method or constructor. To
find out what kind of entity a GIFunctionInfo represents, call
@ref{g-golf-fi-get-flags}.

See also @ref{Callable Info} for information on how to retreive
arguments and other metadata.


@subheading Procedures

Note: in this section, the @var{info} argument is [must be] a pointer to
a @code{GIFunctionInfo}.


@anchor{g-golf-fi-get-flags}
@deffn Procedure g-golf-fi-get-flags info

Returns a list of @ref{%g-golf-fi-flags}.

Obtain the @code{GIFunctionInfoFlags} for @var{info}.
@end deffn


@anchor{g-golf-fi-get-symbol}
@deffn Procedure g-golf-fi-get-symbol info

Returns a string.

Obtain the @samp{symbol} of the function@footnote{As you have noticed
already, since @code{g-golf-fi-get-symbol} returns a string, in the
Glib, GObject and GObject Instrospection worlds, symbol has a different
meaning then in the Lisp/Scheme worlds.  However, since the procedure is
part of the G-Golf low-level API, we decided to keep its name as close
as the original name as possible, given and keeping in mind G-Golf
@ref{Abreviations} conventions.}, which in @code{Glib} terms is the name
of the exported function, @samp{suitable to be used as an argument to
g_module_symbol()}.
@end deffn


@subheading Types and Values


@anchor{%g-golf-fi-flags}
@defivar <gi-enum> %g-golf-fi-flags

An instance of @code{<gi-enum>}, who's members are the scheme
representation of the @code{GIFunctionInfoFlags}:

@indentedblock
@emph{gi-name}: GIFunctionInfoFlags  @*
@emph{scm-name}: gi-function-info-flags  @*
@emph{enum-set}:
@indentedblock
is-method	@*
is-constructor	@*
is-getter	@*
is-setter	@*
wraps-vfunc	@*
throws
@end indentedblock
@end indentedblock
@end defivar
