@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.  Copyright (C) 2019
@c Free Software Foundation, Inc.  See the file g-golf.texi for copying
@c conditions.


@c @defindex ei


@node GObject__
@subsection GObject

G-Golf GObject high level API.@*
The G-Golf integration with the GObject object system.


@subheading Classes

@indentedblock
@table @code
@item @ref{<gobject>}
@end table
@end indentedblock


@subheading Procedures
@c and Methods

@indentedblock
@table @code
@item @ref{gobject-class?}
@end table
@end indentedblock


@subheading Description


@subheading Classes

@anchor{<gobject>}
@deftp Class <gobject>

The base class for GLib’s default object system.

@end deftp


@anchor{gobject-class?}
@deffn Procedure gobject-class? val

Returns #t if @var{val} is a member of the class-subclasses
for @code{<gobject>}. Otherwise, it returns #f.
@end deffn
