@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.
@c Copyright (C) 2016 - 2018 Free Software Foundation, Inc.
@c See the file g-golf.texi for copying conditions.


@node GObject_
@subsection GObject_

G-Golf GObject low level API.@*
GObject — The base object type


@subheading Procedures

@indentedblock
@table @code
@item @ref{g-object-type}
@item @ref{g-object-get-property}
@end table
@end indentedblock


@c @subheading Types and Values

@c @indentedblock
@c @table @code
@c @item @ref{%g-type-fundamental-flags}
@c @end table
@c @end indentedblock


@subheading Object Hierarchy

@indentedblock
GObject           	       @*
@ @ +--- GBinding	       @*
@ @ +--- GInitiallyUnowned     @*
@ @ +--- GTypeModule	       @*
@end indentedblock


@subheading Description

@code{GObject} is the fundamental type providing the common attributes
and methods for all object types in @code{GTK+}, @code{Pango} and other
libraries based on GObject. The GObject class provides methods for
object construction and destruction, property access methods, and signal
support.

Please read the @uref{@value{UGOBJECT-GObject}, GObject} section from
the GObject reference manual for a complete description.


@subheading Procedures

Note: in this section, unless otherwise specified, the @var{object}
argument is [must be] a pointer to a @code{GObject} (instance).


@anchor{g-object-type}
@deffn Procedure g-object-type object

Returns the @var{GType} (the type id) for @var{object}.
@end deffn


@anchor{g-object-get-property}
@deffn Procedure g-object-get-property object property

Returns the @var{property} value for @var{object}.
@end deffn


@c @subheading Types and Values
