@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.
@c Copyright (C) 2016 - 2018 Free Software Foundation, Inc.
@c See the file g-golf.texi for copying conditions.


@node Modules
@subsection Modules


@indentedblock
@table @code
@item @ref{re-export-public-interface}
@end table
@end indentedblock


@anchor{re-export-public-interface}
@defspec re-export-public-interface  . args
Re-export the public interface of a module or modules. Invoked as
@code{(re-export-modules (mod1) (mod2)...)}.
@end defspec
