@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.  Copyright (C) 2019
@c Free Software Foundation, Inc.  See the file g-golf.texi for copying
@c conditions.


@c @defindex ei


@node Import
@subsection Import

G-Golf Import high level API.@*
The G-Golf GIR namespace (Typelib) import high level API.


@subheading Procedures

@indentedblock
@table @code
@item @ref{gi-import}
@item @ref{gi-import-info}
@item @ref{gi-import-by-name}
@end table
@end indentedblock


@subheading Variables

@indentedblock
@table @code
@item @ref{%gi-base-info-types}
@item @ref{%gi-imported-base-info-types}
@end table
@end indentedblock


@c @subheading Description


@subheading Procedures


@anchor{gi-import}
@anchor{gi-import-info}
@anchor{gi-import-by-name}
@deffn Procedure gi-import namespace
@deffnx Procedure gi-import-info info
@deffnx Procedure gi-import-by-name namespace name

Returns nothing.

Respectively imports (and exports their interface) a @var{namespace} (a
GIR Typelib), a specific @var{info} (a pointer to a GIBaseInfo item), or
the (top level) @var{name} GIBaseInfo in @var{namespace} .

The @var{namespace} and @var{name} arguments are case sensitive. It is
an error to call any of these three procedures using an invalid
@var{namespace}, @var{info} and @var{namespace} @var{name} combination.
@end deffn


@subheading Variables


@anchor{%gi-base-info-types}
@anchor{%gi-imported-base-info-types}
@defvar %gi-base-info-types
@defvarx %gi-imported-base-info-types

A (cumulative) list of the distinct (top level) base info types
contained in the imported namespace(s).

These two variables have no other purpose then offering a feedback
about: (a) the (top level) base info types contained in the namespace(s)
passed to @ref{gi-import}; (b) the (top level) base info types that have
effectively been imported - when @code{G-Golf} is complete, both lists
should be identical.

Initially, these variables are empty. As @ref{gi-import},
@ref{gi-import-info} and/or @ref{gi-import-by-name} are being called,
they are filled with new types, which are added to both lists.

Note that theorder in which base info types appear in these two lists is
rrelevant, and may slightly vary, depending on the order of the
namespace used for the successive @ref{gi-import} calls and how complete
is @code{G-Golf}.
@end defvar
