@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.  Copyright (C) 2019
@c Free Software Foundation, Inc.  See the file g-golf.texi for copying
@c conditions.


@c @defindex ei


@node GType
@subsection GType

G-Golf GType high level API.@*
The base of the GObject type system.


@subheading Classes

@indentedblock
@table @code
@item @ref{<gtype-class>}
@item @ref{<gtype-instance>}
@end table
@end indentedblock


@subheading Procedures and Methods

@indentedblock
@table @code
@item @ref{!info}
@item @ref{!namespace}
@item @ref{!gtype-id}
@item @ref{!gtype-name}
@item @ref{!scm-name_}
@item @ref{!g-inst}
@end table
@end indentedblock


@c @subheading Classes

@anchor{<gtype-class>}
@deftp Class <gtype-class>

The @code{metaclass} of all GType classes. Ensures that GType classes
have an @code{info} slot, holding a pointer to a
@code{GIObjectInfo}. Its slots are:

@indentedblock
@table @code
@item @emph{info}
#:accessor !info @*
#:init-keyword #:info @*

@item @emph{namespace}
#:accessor !namespace @*
#:allocation #:virtual

@item @emph{gtype-id}
#:accessor !gtype-id @*
#:allocation #:virtual

@item @emph{gtype-name}
#:accessor !gtype-name @*
#:allocation #:virtual

@item @emph{scm-name}
#:accessor !scm-name @*
#:allocation #:virtual
@end table
@end indentedblock

@end deftp


@anchor{!info}
@deffn Method !info class

Returns the content of the @var{info} slot for @var{class}.
@end deffn


@anchor{!namespace}
@deffn Method !namespace class

Returns the namespace of @var{class}.
@end deffn


@anchor{!gtype-id}
@deffn Method !gtype-id class

Returns the @code{GType} for @var{class}.
@end deffn


@anchor{!gtype-name}
@deffn Method !gtype-name class

Returns the name of the object type for @var{class}.
@end deffn


@anchor{!scm-name_}
@deffn Method !scm-name class

Returns the scheme name of the object type for @var{class}.
@end deffn


@anchor{<gtype-instance>}
@deftp Class <gtype-instance>

The root class of all instantiatable GType classes. Adds a slot,
@code{g-inst}, to instances, which holds a pointer to the C value

@indentedblock
@table @code
@item @emph{g-inst}
#:accessor !g-inst @*
@c #:init-value #f @*
@end table
@end indentedblock

The @var{g-inst} slot is initialized automatically and immutable (to be
precise, it is not meant to be mutated, see @ref{GOOPS Notes and
Conventions}, 'Slots are not Immutable').
@end deftp


@anchor{!g-inst}
@deffn Method !g-inst instance

Returns the content of the @var{g-inst} slot for @var{instance}.
@end deffn
