@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.
@c Copyright (C) 2016 - 2018 Free Software Foundation, Inc.
@c See the file g-golf.texi for copying conditions.


@defindex ci


@node Callable Info
@subsection Callable Info

G-Golf Callable Info low level API.@*
GICallableInfo — Struct representing a callable.


@subheading Procedures

@indentedblock
@table @code
@item @ref{g-callable-info-get-n-args}
@item @ref{g-callable-info-get-arg}
@item @ref{g-callable-info-get-instance-ownership-transfer}
@item @ref{g-callable-info-get-caller-owns}
@item @ref{g-callable-info-get-return-type}
@item @ref{g-callable-info-may-return-null}
@end table
@end indentedblock


@c @subheading Types and Values

@c @indentedblock
@c @table @code
@c @ref{...}
@c @end table
@c @end indentedblock


@subheading Struct Hierarchy

@indentedblock
GIBaseInfoInfo         	                     @*
@ @ +--- GICallableInfo	                     @*
@ @ @ @ @ @ @ @ @ @ @ +--- GIFunctionInfo    @*
@ @ @ @ @ @ @ @ @ @ @ +--- GISignalInfo      @*
@ @ @ @ @ @ @ @ @ @ @ +--- GIVFuncInfo
@end indentedblock


@subheading Description

@code{GICallableInfo} represents an entity which is callable. Currently
a function (@code{GIFunctionInfo}), virtual function,
(@code{GIVFuncInfo}) or callback (@code{GICallbackInfo}).

A callable has a list of arguments (@code{GIArgInfo}), a return type,
direction and a flag which decides if it returns null.


@subheading Procedures

Note: in this section, the @var{info} argument is [must be] a pointer to
a @code{GICallableInfo}.


@anchor{g-callable-info-get-n-args}
@deffn Procedure g-callable-info-get-n-args info

Returns the number of arguments this @var{info} expects.

Obtain the number of arguments (both IN and OUT) for this
@var{info}.
@end deffn


@anchor{g-callable-info-get-arg}
@deffn Procedure g-callable-info-get-arg info n

Returns a pointer to the @var{n}th @code{GIArgInfo} of @var{info}.

It must be freed by calling @ref{g-base-info-unref} when done accessing
the data.
@end deffn


@anchor{g-callable-info-get-instance-ownership-transfer}
@deffn Procedure g-callable-info-get-instance-ownership-transfer info

Returns a @code{GITransfer} enumerated value.

Obtains the ownership transfer for the instance argument. See
@ref{%gi-transfer} for the list of possible values.
@end deffn


@anchor{g-callable-info-get-caller-owns}
@deffn Procedure g-callable-info-get-caller-owns info

Returns a @code{GITransfer} enumerated value.

See whether the caller owns the return value of this callable. See
@ref{%gi-transfer} for the list of possible values.
@end deffn


@anchor{g-callable-info-get-return-type}
@deffn Procedure g-callable-info-get-return-type info

Returns a pointer to the @code{GITypeInfo}.

It must be freed by calling @ref{g-base-info-unref} when done accessing
the data.
@end deffn


@anchor{g-callable-info-may-return-null}
@deffn Procedure g-callable-info-may-return-null info

Returns @code{#t} if the callable @var{info} could return @code{NULL}.

See if a callable could return NULL.
@end deffn


@c @subheading Types and Values
