@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.
@c Copyright (C) 2016 Free Software Foundation, Inc.


@copying
This manual documents GNU G-Golf version @value{VERSION}.

Copyright (C) 2016 Free Software Foundation, Inc.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A
copy of the license is included in the section entitled ``GNU Free
Documentation License.''
@end copying


@defindex bi


@node Base Info
@subsection Base Info

G-Golf Base Info low level API.@*
GIBaseInfo — Base struct for all GITypelib structs.


@subheading Description

@code{GIBaseInfo} is the common base struct of all other *Info structs
accessible through the @code{GIRepository API}.

Most @code{GIRepository APIs} returning a @code{GIBaseInfo} is actually
creating a new struct, in other words, @ref{golf-bi-unref} has to be
called when done accessing the data. @code{GIBaseInfos} are normally
accessed by calling either @ref{golf-ir-find-by-name},
@ref{golf-ir-find-by-gtype} or @ref{golf-ir-get-info}.

@example
@strong{Example:} Getting the Button of the Gtk typelib
@end example

@lisp
,use (g-golf gi)
(golf-ir-require "Gtk")
(golf-ir-find-by-name "Gtk" "Button")
@print{}
$4 = #<pointer 0x20e0000>
... use button info ...
(golf-bi-unref $4)
@end lisp


@subheading Struct Hierarchy

@indentedblock
GIBaseInfo           	       @*
@ @ +--- GIArgInfo	       @*
@ @ +--- GICallableInfo	       @*
@ @ +--- GIConstantInfo        @*
@ @ +--- GIFieldInfo           @*
@ @ +--- GIPropertyInfo        @*
@ @ +--- GIRegisteredTypeInfo  @*
@ @ +--- GITypeInfo
@end indentedblock

@subheading Procedures

@indentedblock
@table @code
@item @ref{golf-bi-ref}
@item @ref{golf-bi-unref}
@item @ref{golf-bi-equal}
@item @ref{golf-bi-get-type}
@item @ref{golf-bi-get-typelib}
@item @ref{golf-bi-get-namespace}
@item @ref{golf-bi-get-name}
@item @ref{golf-bi-get-attribute}
@item @ref{golf-bi-iterate-attributes}
@item @ref{golf-bi-get-container}
@item @ref{golf-bi-is-deprecated}
@end table
@end indentedblock

Note: in this section, the @var{info}, @var{info1} and @var{info2}
arguments are [must be] pointers to a @code{GIBaseInfo}.

@anchor{golf-bi-ref}
@deffn Procedure golf-bi-ref info

Returns the same @var{info}.

Increases the reference count of @var{info}.
@end deffn


@anchor{golf-bi-unref}
@deffn Procedure golf-bi-unref info

Returns nothing.

Decreases the reference count of @var{info}. When its reference count
drops to 0, the @var{info} is freed.
@end deffn


@anchor{golf-bi-equal}
@deffn Procedure golf-bi-equal info1 info2

Returns #t if and only if @var{info1} equals @var{info2}.

Compares two @code{GIBaseInfo}.

Using pointer comparison is not practical since many functions return
different instances of @code{GIBaseInfo} that refers to the same part of
the @code{TypeLib}: use this procedure instead to do @code{GIBaseInfo}
comparisons.
@end deffn

@anchor{golf-bi-get-type}
@deffn Procedure golf-bi-get-type info

Returns the info type of @var{info}.
@end deffn


@anchor{golf-bi-get-typelib}
@deffn Procedure golf-bi-get-typelib info

Returns a pointer to the @code{GITypelib} the @var{info} belongs to.
@end deffn


@anchor{golf-bi-get-namespace}
@deffn Procedure golf-bi-get-namespace info

Returns the namespace of @var{info}
@end deffn


@anchor{golf-bi-get-name}
@deffn Procedure golf-bi-get-name info

Returns the name of @var{info} or @code{#f} if it lacks a name.

What the name represents depends on the @code{GIInfoType} of the
info. For instance for @code{GIFunctionInfo} it is the name of the
function.
@end deffn


@anchor{golf-bi-get-attribute}
@deffn Procedure golf-bi-get-attribute info name

Returns the value of the attribute or @code{#f} if not such attribute
exists.
@end deffn


@anchor{golf-bi-iterate-attributes}
@deffn Procedure golf-bi-iterate-attributes info proc

Returns nothing.

Iterate and calls @var{proc} over all attributes associated with this
node. @var{proc} must be a procedure of two arguments, the @var{name}
and the @var{value} of the attribute.
@end deffn


@anchor{golf-bi-get-container}
@deffn Procedure golf-bi-get-container info

Returns a pointer to a @code{GIBaseInfo}.

The container is the parent @code{GIBaseInfo}. For instance, the parent
of a @code{GIFunctionInfo} is an @code{GIObjectInfo} or
@code{GIInterfaceInfo}.
@end deffn


@anchor{golf-bi-is-deprecated}
@deffn Procedure golf-bi-is-deprecated info

Returns @code{#t} if deprecated.

Obtain whether @var{info} represents a metadata which is deprecated or
not.
@end deffn


@subheading Types and Values

@indentedblock
@table @code
@item @ref{%golf-bi-info-type}
@end table
@end indentedblock


@anchor{%golf-bi-info-type}
@defvar %golf-bi-info-type

An instance of @code{<enum>}, who's members are the scheme
representation of the @code{GIInfoType}:

@indentedblock
invalid		@*
function	@*
callback	@*
struct		@*
boxed		@*
enum		@*
flags		@*
object		@*
interface	@*
constant	@*
error-domain	@*
union		@*
value		@*
signal		@*
vfunc		@*
property	@*
field		@*
arg		@*
type		@*
unresolved
@end indentedblock
@end defvar
