@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.
@c Copyright (C) 2016 Free Software Foundation, Inc.


@copying
This manual documents GNU G-Golf version @value{VERSION}.

Copyright (C) 2016 Free Software Foundation, Inc.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A
copy of the license is included in the section entitled ``GNU Free
Documentation License.''
@end copying


@node API Reference
@chapter API Reference

@c G-Golf Reference Manual still is a mock-up: any help is more then
@c welcome to improve this situation, thanks!


@menu
* API Overview::
* GObject Introspection::
* GObject::
* Glib::
* Support::
@end menu


@node API Overview
@section API Overview

@include api-overview.texi


@node GObject Introspection
@section GObject Introspection

@include api-gir.texi


@node GObject
@section GObject

@include api-gobject.texi


@node Glib
@section Glib

@c @include api-glib.texi


@node Support
@section Support

@include api-support.texi
