@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.
@c Copyright (C) 2016 - 2018 Free Software Foundation, Inc.
@c See the file g-golf.texi for copying conditions.


@node API Reference
@chapter API Reference

@c G-Golf Reference Manual still is a mock-up: any help is more then
@c welcome to improve this situation, thanks!


@menu
* API Overview::
* GObject Introspection::
* GObject::
* Glib::
* Support::
@end menu


@node API Overview
@section API Overview

@include api-overview.texi


@node GObject Introspection
@section GObject Introspection

@include api-gir.texi


@node GObject
@section GObject

@include api-gobject.texi


@node Glib
@section Glib

@c @include api-glib.texi


@node Support
@section Support

@include api-support.texi
