\input texinfo
@c -*- mode: texinfo; coding: utf-8 -*-
@c This is part of the GNU G-Golf Reference Manual.
@c Copyright (C) 2016 Free Software Foundation, Inc.


@page
@node Concept Index
@unnumbered Concept Index

This index contains concepts, keywords and non-Schemey names for several
features, to make it easier to locate the desired sections.

@printindex cp


@page
@node Procedure Index
@unnumbered Procedure Index

This is an alphabetical list of all the procedures, methods and macros
in G-Golf.

@c @subheading Repository
@c @printindex ir

@c @subheading Base Info
@c @printindex bi

@printindex fn


@page
@node Variable Index
@unnumbered Variable Index

This is an alphabetical list of all the important variables and
constants in G-Golf.

@printindex vr


@page
@node Type Index
@unnumbered Type Index

This is an alphabetical list of all the important data types defined in
the G-Golf.

@printindex tp

