@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.
@c Copyright (C) 2016 - 2018 Free Software Foundation, Inc.
@c See the file g-golf.texi for copying conditions.


@node Introduction
@chapter Introduction

@menu
* About G-Golf::
@c * Description::
@c * What else::
@c * Savannah::
* Obtaining and Installing G-Golf::
* Contact::
* Reporting Bugs::
@end menu


@node About G-Golf
@section About G-Golf

GNU G-Golf @*
Gnome: (Guile Object Library for).


@subheading Description

G-Golf is a Guile@footnote{GNU @uref{@value{UGUILE}, Guile}@*an
interpreter and compiler for the @uref{@value{USCHEME}, Scheme}
programming language.} Object Library for Gnome.

G-Golf is a library, composed of a direct binding to
@uref{@value{UGI-wiki}, GObject Introspection} plus a higher
functionality layer, which, importing Gnome libraries, makes GOBject
classes and methods GOOPS citizen (@pxref{GOOPS,,, guile, The GNU Guile
Reference Manual}).

G-Golf is a tool to develop modern graphical applications in Guile
Scheme.


@subheading Savannah

GNU G-Golf also has a @uref{@value{UG-GOLF-SAVANNAH}, Savannah} project
page.


@node Obtaining and Installing G-Golf
@section Obtaining and Installing G-Golf

GNU G-Golf can be obtained from the following archive site
@uref{@value{UG-GOLF-RELEASES}}.  The file will be named
g-golf-version.tar.gz. The current version is @value{VERSION}, so the
file you should grab is:

@tie{}@tie{}@tie{}@tie{}@uref{@value{UG-GOLF-LATEST}}


@subheading Dependencies

GNU G-Golf needs the following software to run:

@itemize @bullet

@item
Autoconf >= 2.69
@item
Automake >= 1.14
@item
Makeinfo >= 6.3
@item
@uref{@value{UGUILE}, Guile} >= 2.0.14  [allows 2.2 3.0]
@item
@uref{@value{UGUILE-LIB}, Guile-Lib} >= 0.2.5
@item
@uref{@value{UGLIB}, Glib-2.0} >= 2.48.0
@item
@uref{@value{UGOBJECT}, Gobject-2.0} >= 2.48.0
@item 
@uref{@value{UGI}, GObject-Introspection-1.0} >= 1.48.0
@end itemize


@subheading Quickstart

Assuming you have satisfied the dependencies, open a terminal and
proceed with the following steps:

@example
cd <download-path>
tar zxf g-golf-@value{VERSION}.tar.gz
cd g-golf-@value{VERSION}
./configure [--prefix=/your/prefix]
make
make install
@end example

Happy G-Golf!


@*
@strong{Notes:}

@enumerate
@item
The @code{default} and @code{--prefix} installation locations for source
modules and compiled files (in the absence of
@code{--with-guile-site=yes}) are:

@example
$(datadir)/g-golf
$(libdir)/g-golf/guile/$(GUILE_EFFECTIVE_VERSION)/site-ccache
@end example

If you pass @code{--with-guile-site=yes}, these locations become the
Guile site and site-ccache directories, respectively.

The configure step reports these locations as the content of the
@code{sitedir} and @code{siteccachedir} variables, respectivelly the
source modules and compiled files install locations. After installation,
you may consult these variables using pkg-config:

@example
pkg-config g-golf-1.0 --variable=sitedir
pkg-config g-golf-1.0 --variable=siteccachedir
@end example

You will need - unless you have used @code{--with-guile-site=yes}, or
unless these locations are already 'known' by Guile - to define or
augment your @code{GUILE_LOAD_PATH} and @code{GUILE_COMPILED_PATH}
environment variables with these locations, respectively (or
@code{%load-path} and @code{%load-compiled-path} at run time if you
prefer@footnote{In this case, you may as well decide to either alter
your @file{$HOME/.guile} personal file, or, if you are working in a
mult-user environmet, you may also opt for a global configuration. In
this case, the file must be named @file{init.scm} and placed it here
(evaluate the following expression in a terminal): @code{guile -c
"(display (%global-site-dir))(newline)"}.}  (See
@uref{@value{UGUILE-ENV-VARS}, Environment Variables} and
@uref{@value{UGUILE-LOAD-PATH}, Load Path} in the Guile Reference
Manual).

@item
G-Golf also installs its @code{libg-golf.*} library files, in
@code{$(libdir)}. The configure step reports its location as the content
of the @code{libdir} variable, which depends on on the content of the
@code{prefix} and @code{exec_prefix} variables (also reported). After
nstallation, you may consult these variables using pkg-config:

@example
pkg-config g-golf-1.0 --variable=prefix
pkg-config g-golf-1.0 --variable=exec_prefix
pkg-config g-golf-1.0 --variable=libdir
@end example

You will need - unless the @code{$(libdir)} location is already 'known'
by your system - to either define or augment your
@code{$LD_LIBRARY_PATH} environment variable, or alter the
@file{/etc/ld.so.conf} (or add a file in @file{/etc/ld.so.conf.d}) and
run (as root) @code{ldconfig}, so that G-Golf finds its
@code{libg-golf.*} library files@footnote{Contact your administrator
if you opt for the second solution but don't have @code{write}
priviledges on your system.}.
@c @ifhtml
@c @*@*
@c @end ifhtml

@item
To install G-Golf, you must have write permissions to the default or
@code{$(prefix)} directory and its subdirs, as well as to both Guile's
site and site-ccache directories if @code{--with-guile-site=yes} was
passed.
@ifhtml
@*@*
@end ifhtml

@item
Like for any other GNU Tool Chain compatible software, you may install
the documentation locally using @code{make install-info}, @code{make
install-html} and/or @code{make install-pdf}.
@ifhtml
@*@*
@end ifhtml

@item
Last but not least :), G-Golf comes with a @code{test-suite}, which we
recommend you to run (especially before @ref{Reporting Bugs}):

@example
make check
@end example
@end enumerate


@node Contact
@section Contact


@subheading Mailing list

G-Golf uses the following mailing list:

@itemize @bullet
@item g-golf-user at gnu dot org
@end itemize

You can (un)subscribe to the list by following instructions on the
@uref{@value{UG-GOLF-LISTINFO}, list information page}.


@subheading IRC

Most of the time you can find me on irc, channel @emph{#guile},
@emph{#guix} and @emph{#scheme} on @emph{irc.freenode.net},
@emph{#clutter} on @emph{irc.gnome.org}, under the nickname
@strong{daviid}.



@node Reporting Bugs
@section Reporting Bugs

G-Golf has a @uref{@value{UG-GOLF-BUGS-TRACKER}, bugs tracker}. You
may send your bugs report here:

@itemize @bullet
@item bug-g-golf at gnu dot org
@end itemize

You can (un)subscribe to the bugs report list by following instructions
on the @uref{@value{UG-GOLF-BUGS-LISTINFO}, list information page}.

