@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.
@c Copyright (C) 2016 - 2018 Free Software Foundation, Inc.
@c See the file g-golf.texi for copying conditions.


@node Introduction
@chapter Introduction

@menu
* About G-Golf::
@c * Description::
@c * What else::
@c * Savannah::
* Obtaining and Installing G-Golf::
* Contact::
* Reporting Bugs::
@end menu


@node About G-Golf
@section About G-Golf

GNU G-Golf @*
Gnome: (Guile Object Library for).


@subheading Description

G-Golf is a Guile@footnote{GNU @uref{@value{UGUILE}, Guile}@*an
interpreter and compiler for the @uref{@value{USCHEME}, Scheme}
programming language.} Object Library for Gnome.

G-Golf is a library, composed of a direct binding to
@uref{@value{UGI-wiki}, GObject Introspection} plus a higher
functionality layer, which, importing Gnome libraries, makes GOBject
classes and methods GOOPS citizen (@pxref{GOOPS,,, guile, The GNU Guile
Reference Manual}).

G-Golf is a tool to develop modern graphical applications in Guile
Scheme.


@subheading What else

G-Golf is entirely written in @uref{@value{UGUILE}, Guile}, no C
code.


@subheading Savannah

GNU G-Golf also has a @uref{@value{UG-GOLF-SAVANNAH}, Savannah} project
page.


@node Obtaining and Installing G-Golf
@section Obtaining and Installing G-Golf

GNU G-Golf can be obtained from the following archive site
@uref{@value{UG-GOLF-RELEASES}}.  The file will be named
g-golf-version.tar.gz. The current version is @value{VERSION}, so the
file you should grab is:

@tie{}@tie{}@tie{}@tie{}@uref{@value{UG-GOLF-LATEST}}


@subheading Dependencies

GNU G-Golf needs the following software to run:

@itemize @bullet

@item
Autoconf >= 2.69
@item
Automake >= 1.14
@item
@uref{@value{UGUILE}, Guile} >= 2.0.12
@item 
@uref{@value{UGI}, GObject-Introspection-1.0} >= 1.48.0
@item
@uref{@value{UGLIB}, Glib-2.0} >= 2.48.0
@item
@uref{@value{UGOBJECT}, Gobject-2.0} >= 2.48.0
@end itemize


@subheading Quickstart

Assuming you have satisfied the dependencies, open a terminal and
proceed with the following steps:

@example
cd <download-path>
tar zxf g-golf-@value{VERSION}.tar.gz
cd g-golf-@value{VERSION}
./configure [--prefix=/your/prefix]
make
make install
@end example

Happy G-Golf!

@*
@strong{Notes:}

@enumerate
@item
In the above @code{configure} step, @code{--prefix=/your/prefix} is
optional.  The default value is @code{/usr/local}.  As an example, you
could use

@example
./configure --prefix=/opt
@end example

@item
To install GNU G-Golf, you must have @code{write permissions} for
@code{$prefix}, Guile's global site and site-ccache directories.
@ifhtml
@*@*
@end ifhtml

@item
GNU G-Golf's modules are installed in Guile's global site directory.  If
you want to know its location, enter the following expression in a
terminal:

@example
guile -c "(display (%global-site-dir)) (newline)"
@end example

@item
G-Golf's compiled modules are installed in the Guile's
@code{site-ccache} directory.  If you want to know its location, enter
the following expression in a terminal:

@example
guile -c "(display (%site-ccache-dir)) (newline)"
@end example

@item
Like for any other GNU Tool Chain compatible software, you may install
the documentation locally using @code{make install-info}, @code{make
install-html} and/or @code{make install-pdf}. The documentation is
installed in @code{$prefix/share/doc/g-golf}
@end enumerate


@node Contact
@section Contact


@subheading Mailing list

G-Golf uses the following mailing list:

@itemize @bullet
@item g-golf-user at gnu dot org
@end itemize

You can (un)subscribe to the list by following instructions on the
@uref{@value{UG-GOLF-LISTINFO}, list information page}.


@subheading IRC

Most of the time you can find me on irc, channel @emph{#guile},
@emph{#guix} and @emph{#scheme} on @emph{irc.freenode.net},
@emph{#clutter} on @emph{irc.gnome.org}, under the nickname
@strong{daviid}.



@node Reporting Bugs
@section Reporting Bugs

G-Golf has a @uref{@value{UG-GOLF-BUGS-TRACKER}, bugs tracker}. You
may send your bugs report here:

@itemize @bullet
@item bug-g-golf at gnu dot org
@end itemize

You can (un)subscribe to the bugs report list by following instructions
on the @uref{@value{UG-GOLF-BUGS-LISTINFO}, list information page}.

