@c -*-texinfo-*-
@c This is part of the GNU G-Golf Reference Manual.
@c Copyright (C) 2016 - 2018 Free Software Foundation, Inc.
@c See the file g-golf.texi for copying conditions.


@node Using G-Golf
@chapter Using G-Golf

G-Golf Reference Manual still is a mock-up: any help is more then
welcome to improve this situation, thanks!
